language: node_js
node_js:
  - "10"
  - "8"
  - "6"
notifications:
  email: false
sudo: false
addons:
  apt:
    packages:
    - expect
before_script:
  - npm prune
  - bin/e2e-test.sh
after_success:
  - npm run coverage
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
