language: node_js

matrix:
  include:
    - node_js: "0.8"
      before_install: npm  update -g  npm
      # old versions of NPM don't include support for `^` dependency prefixes in package.json
    - node_js: "0.10"
    - node_js: "0.12"
    - node_js: "4.0"
    - node_js: "4.1"
    - node_js: "4.2"
notifications:
  email: false

sudo: false
